name: Playwright Tests - Allure TestOps
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or staging)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://findco.testops.cloud/
  ALLURE_PROJECT_ID: 166
  ALLURE_RESULTS: allure-results

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create .env.${{ github.event.inputs.environment }} file
        run: |
          if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
            echo "${{ secrets.STAGING_DOT_ENV }}" > .env.staging
          elif [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "${{ secrets.DEV_DOT_ENV }}" > .env.dev
          fi

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          export ALLURE_ENDPOINT=${{ env.ALLURE_ENDPOINT }}
          export ALLURE_TOKEN=${{ secrets.ALLURE_TOKEN }}
          export ALLURE_PROJECT_ID=${{ env.ALLURE_PROJECT_ID }}
          export ALLURE_LAUNCH_NAME="Nucleus regression suite - ${{ github.event.inputs.environment }}"
          export ALLURE_RESULTS=${{ env.ALLURE_RESULTS }}
          export ALLURE_LAUNCH_TAGS=""
          allurectl watch -- `TEST_ENV=${{github.event.inputs.environment}} npx playwright test` 
