name: Playwright Tests - Allure TestOps
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or staging)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://findco.testops.cloud/
  ALLURE_PROJECT_ID: 166
  ALLURE_RESULTS: allure-results

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Ensure environment variables are set
        run: echo $ALLURE_TOKEN $ALLURE_JOB_RUN_ID $ALLURE_ENDPOINT $ALLURE_PROJECT_ID $ALLURE_RESULTS

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create .env file
        run: echo "${{secrets.DOT_ENV}}" > .env

      - name: Run Playwright tests
        run: |
          allurectl watch -- `npx playwright test` --config=playwright.config.ts --token=74a17ee3-3c96-45e5-acff-ca47464009ad --job-run-id=${{ env.ALLURE_JOB_RUN_ID }} --endpoint=${{ env.ALLURE_ENDPOINT }} --project-id=${{ env.ALLURE_PROJECT_ID }} --results-dir=${{ env.ALLURE_RESULTS }}
