name: Playwright Tests - GH Pages Allure Report
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or staging)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create .env file
        run: echo "${{secrets.DOT_ENV}}" > .env
      - name: Run Playwright tests
        run: TEST_ENV=${{github.event.inputs.environment}} npx playwright test --workers=6
      - name: Generate Allure Report
        run:  npx allure generate allure-results --clean -o allure-report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
      - name: Display GitHub Pages URL
        if: always()
        run:
          echo "GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"