name: Common Allure Reports
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      allure_launch_name:
        required: true
        type: string
    secrets:
      ALLURE_TOKEN:
        required: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*


#      - name: Create .env file
#        run: |
#            echo "${{ secrets.DEV_DOT_ENV }}" > .env.dev;
#            echo "${{ secrets.STAGING_DOT_ENV }}" > .env.staging;



      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers (only edge)
        run: npx playwright install msedge --with-deps


      - name: Run Playwright tests
        env:
          DEBUG: pw:api
          ALLURE_ENDPOINT: https://findco.testops.cloud/
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: "166"
          ALLURE_LAUNCH_NAME: ${{ inputs.allure_launch_name }}
          ALLURE_RESULTS: allure-results
        run: |
          allurectl watch -- TEST_ENV=${{ inputs.environment }} npx playwright test --retries=3 --reporter=allure-playwright \
            --log DEBUG \
            --job-name "${{ github.workflow }}" \
            --launch-name "$ALLURE_LAUNCH_NAME" \
            --launch-tags "${{ inputs.environment }}" \
