name: Dev - Playwright Tests - Allure TestOps
on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
  ALLURE_RESULTS: "allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  call-common:
    uses: ./.github/workflows/common-allure-reports.yml
    with:
      environment: dev
      allure_launch_name: "[Staging] Nucleus regression suite"
    secrets:
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}