name: Playwright Tests - Allure TestOps (Dev)
on:
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common-allure-reports.yml
    with:
      environment: dev
      allure_launch_name: "Nucleus regression suite - dev"
    secrets:
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}