name: Playwright Tests - Allure TestOps (Staging)
on:
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common-allure-reports.yml
    with:
      environment: staging
      allure_launch_name: "Nucleus regression suite - staging"
    secrets:
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}